
/* AUTO-GENERATED by gen_isr_tables.py, do not edit! */

#include <zephyr/toolchain.h>
#include <zephyr/linker/sections.h>
#include <zephyr/sw_isr_table.h>
#include <zephyr/arch/cpu.h>

_Z_ISR_DIRECT_TABLE_ENTRY(0, _isr_wrapper, ".irq_spurious.0x0");
_Z_ISR_DIRECT_TABLE_ENTRY(1, _isr_wrapper, ".irq_spurious.0x1");
_Z_ISR_DIRECT_TABLE_ENTRY(2, _isr_wrapper, ".irq_spurious.0x2");
_Z_ISR_DIRECT_TABLE_ENTRY(3, _isr_wrapper, ".irq_spurious.0x3");
_Z_ISR_DIRECT_TABLE_ENTRY(4, _isr_wrapper, ".irq_spurious.0x4");
_Z_ISR_DIRECT_TABLE_ENTRY(5, _isr_wrapper, ".irq_spurious.0x5");
_Z_ISR_DIRECT_TABLE_ENTRY(6, _isr_wrapper, ".irq_spurious.0x6");
_Z_ISR_DIRECT_TABLE_ENTRY(7, _isr_wrapper, ".irq_spurious.0x7");
/* ISR: 8 implemented in app. */
_Z_ISR_DIRECT_TABLE_ENTRY(9, _isr_wrapper, ".irq_spurious.0x9");
_Z_ISR_DIRECT_TABLE_ENTRY(10, _isr_wrapper, ".irq_spurious.0xa");
_Z_ISR_DIRECT_TABLE_ENTRY(11, _isr_wrapper, ".irq_spurious.0xb");
_Z_ISR_DIRECT_TABLE_ENTRY(12, _isr_wrapper, ".irq_spurious.0xc");
_Z_ISR_DIRECT_TABLE_ENTRY(13, _isr_wrapper, ".irq_spurious.0xd");
_Z_ISR_DIRECT_TABLE_ENTRY(14, _isr_wrapper, ".irq_spurious.0xe");
_Z_ISR_DIRECT_TABLE_ENTRY(15, _isr_wrapper, ".irq_spurious.0xf");
_Z_ISR_DIRECT_TABLE_ENTRY(16, _isr_wrapper, ".irq_spurious.0x10");
_Z_ISR_DIRECT_TABLE_ENTRY(17, _isr_wrapper, ".irq_spurious.0x11");
_Z_ISR_DIRECT_TABLE_ENTRY(18, _isr_wrapper, ".irq_spurious.0x12");
_Z_ISR_DIRECT_TABLE_ENTRY(19, _isr_wrapper, ".irq_spurious.0x13");
_Z_ISR_DIRECT_TABLE_ENTRY(20, _isr_wrapper, ".irq_spurious.0x14");
_Z_ISR_DIRECT_TABLE_ENTRY(21, _isr_wrapper, ".irq_spurious.0x15");
_Z_ISR_DIRECT_TABLE_ENTRY(22, _isr_wrapper, ".irq_spurious.0x16");
_Z_ISR_DIRECT_TABLE_ENTRY(23, _isr_wrapper, ".irq_spurious.0x17");
_Z_ISR_DIRECT_TABLE_ENTRY(24, _isr_wrapper, ".irq_spurious.0x18");
_Z_ISR_DIRECT_TABLE_ENTRY(25, _isr_wrapper, ".irq_spurious.0x19");
_Z_ISR_DIRECT_TABLE_ENTRY(26, _isr_wrapper, ".irq_spurious.0x1a");
_Z_ISR_DIRECT_TABLE_ENTRY(27, _isr_wrapper, ".irq_spurious.0x1b");
_Z_ISR_DIRECT_TABLE_ENTRY(28, _isr_wrapper, ".irq_spurious.0x1c");
_Z_ISR_DIRECT_TABLE_ENTRY(29, _isr_wrapper, ".irq_spurious.0x1d");
_Z_ISR_TABLE_ENTRY(0, z_irq_spurious, NULL, ".isr_generated.0x0");
_Z_ISR_TABLE_ENTRY(1, z_irq_spurious, NULL, ".isr_generated.0x1");
_Z_ISR_TABLE_ENTRY(2, z_irq_spurious, NULL, ".isr_generated.0x2");
_Z_ISR_TABLE_ENTRY(3, z_irq_spurious, NULL, ".isr_generated.0x3");
_Z_ISR_TABLE_ENTRY(4, z_irq_spurious, NULL, ".isr_generated.0x4");
/* ISR: 5 implemented in app in ".irq.WEST_TOPDIR/zephyr/drivers/clock_control/clock_control_nrf.c.0" section. */
_Z_ISR_TABLE_ENTRY(6, z_irq_spurious, NULL, ".isr_generated.0x6");
_Z_ISR_TABLE_ENTRY(7, z_irq_spurious, NULL, ".isr_generated.0x7");
_Z_ISR_TABLE_ENTRY(8, z_irq_spurious, NULL, ".isr_generated.0x8");
/* ISR: 9 implemented in app in ".irq.WEST_TOPDIR/zephyr/drivers/entropy/entropy_nrf5.c.0" section. */
/* ISR: 10 implemented in app in ".irq.WEST_TOPDIR/zephyr/drivers/gpio/gpio_nrfx.c.0" section. */
_Z_ISR_TABLE_ENTRY(11, z_irq_spurious, NULL, ".isr_generated.0xb");
_Z_ISR_TABLE_ENTRY(12, z_irq_spurious, NULL, ".isr_generated.0xc");
/* ISR: 13 implemented in app in ".irq.WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/ecb.c.0" section. */
_Z_ISR_TABLE_ENTRY(14, z_irq_spurious, NULL, ".isr_generated.0xe");
_Z_ISR_TABLE_ENTRY(15, z_irq_spurious, NULL, ".isr_generated.0xf");
_Z_ISR_TABLE_ENTRY(16, z_irq_spurious, NULL, ".isr_generated.0x10");
/* ISR: 17 implemented in app in ".irq.WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c.3" section. */
/* ISR: 18 implemented in app in ".irq.WEST_TOPDIR/zephyr/drivers/mbox/mbox_nrfx_ipc.c.0" section. */
/* ISR: 19 implemented in app in ".irq.WEST_TOPDIR/zephyr/drivers/serial/uart_nrfx_uarte.c.3" section. */
_Z_ISR_TABLE_ENTRY(20, z_irq_spurious, NULL, ".isr_generated.0x14");
_Z_ISR_TABLE_ENTRY(21, z_irq_spurious, NULL, ".isr_generated.0x15");
/* ISR: 22 implemented in app in ".irq.WEST_TOPDIR/zephyr/drivers/timer/nrf_rtc_timer.c.0" section. */
_Z_ISR_TABLE_ENTRY(23, z_irq_spurious, NULL, ".isr_generated.0x17");
_Z_ISR_TABLE_ENTRY(24, z_irq_spurious, NULL, ".isr_generated.0x18");
_Z_ISR_TABLE_ENTRY(25, z_irq_spurious, NULL, ".isr_generated.0x19");
_Z_ISR_TABLE_ENTRY(26, z_irq_spurious, NULL, ".isr_generated.0x1a");
_Z_ISR_TABLE_ENTRY(27, z_irq_spurious, NULL, ".isr_generated.0x1b");
/* ISR: 28 implemented in app in ".irq.WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c.5" section. */
_Z_ISR_TABLE_ENTRY(29, z_irq_spurious, NULL, ".isr_generated.0x1d");
